### ISSUE TITLE
Value: "System.Exception: DotDumper stagnated and is shutting down!"

### ISSUE THREAD

**Issue by x00tox01** [advanced-threat-research/DotDumper#1]
Getting the above error while running Dotdumper for file.
File is MSIL Downloader. 

https://www.virustotal.com/gui/file/60caf6d279300a2c1e2a00d36893641b0f908fc20366bac537263e91ce0a0fa1
(I tried uploading to malware Bazaar but not succeeded)

**Comment by ThisIsLibra** [comment]
Hello,

The [stagnation handler](https://github.com/advanced-threat-research/DotDumper/blob/main/DotDumper/Helpers/StagnationHandler.cs) is a lesser documented part of the code. In short: there are 3 stages in the handler. If no log is received in 20 seconds, the next stage is set. If the third stage is reached, meaning a minute has passed without any logging from DotDumper, the sample is terminated with the message you shared above. This is likely to happen after the sample used interop calls to inject a next stage in a process.

The reason to terminate DotDumper after the 60 second stagnation, is because the external injection call cannot be followed, as it is not residing within DotDumper's process. When using DotDumper in a sandbox to automate the extraction of dropped files, the sandbox will only return early if the submitted sample terminates. Since DotDumper wont shut down on its own in this case, the stagnation handler was created. This saves time during the dynamic execution in the sandbox.

This is a bit of a spoiler, but coming May, an update to improve this detection will be made public.

**Comment by x00tox01** [comment]
Thanks for the Response.
You Explained it very nice.
I Will be waiting for the Next Update.
I uses your tool on daily basis. Its very useful n Needful for .Net Analysis as Obfuscation and multi-stage malware are very frequent these days.
(Till Next update I will Use -raceTime to solve issue )

**Comment by ThisIsLibra** [comment]
The `-raceTime` flag is used for a different purpose, as it sets the required time between the disabling and enabling of the invoke hooks. I'd not suggest you change it, unless the hooks themselves aren't working, but I assume they do based on your earlier comments.

I might add a flag to enable/disable the stagnation handler, but I think that in 99% of the cases, there is no point in waiting longer than the stagnation handler's trigger time.

If you have any other suggestions or ideas, feel free to share them, preferably in different issues you open in this repository, so I can keep things organised.

Cheers,
Max

**Comment by x00tox01** [comment]
Ok Thanks.
Will Do the same.
